/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { OrderType } from './enums';
import { TransactionAmount } from './transaction-amount.model';

export interface Effect {
    effect: string;
    type: OrderType;
    seq?: number;
    price?: string;
    pair?: string;
    counterparty?: string;
    amount: TransactionAmount;
}

