/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

// generate enum based on strings instead of numbers
// (see https://blog.rsuter.com/how-to-implement-an-enum-with-string-values-in-typescript/)
export enum example_enum {
    example = <any>"example",
}

export enum state {
    validated = <any>"validated",
    pending = <any>"pending",
}


