/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

// generate enum based on strings instead of numbers
// (see https://blog.rsuter.com/how-to-implement-an-enum-with-string-values-in-typescript/)
export enum example_enum {
    example = <any>"example",
}

export enum PaymentState {
    validated = <any>"validated",
    pending = <any>"pending",
}

export enum PaymentDirection {
    incoming = <any>"incoming",
    outgoing = <any>"outgoing",
}

export enum OrderType {
    sell = <any>"sell",
    buy = <any>"buy",
}

export enum OrderState {
    validated = <any>"validated",
    pending = <any>"pending",
}

export enum TransactionType {
    payment = <any>"payment",
    OfferCreate = <any>"OfferCreate",
    OfferCancel = <any>"OfferCancel",
    trustset = <any>"trustset",
    offer_create = <any>"offer_create",
    offer_cancel = <any>"offer_cancel",
}

export enum server_state {
    syncing = <any>"syncing",
    proposing = <any>"proposing",
}


