/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { TransactionItem } from './transaction-item.model';

export interface GetTransactionListResponseBody {
    transactions: Array<TransactionItem>;
    success: boolean;
}

