/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Wallet } from './wallet.model';

export interface GetNewWalletResponseBody {
    success: boolean;
    wallet: Wallet;
}

