/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */


export interface GetStatusResponseBody {
    sdchaind_server_status: object;
    success: boolean;
}

