/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { OrderType } from './enums';
import { PaymentDirection } from './enums';
import { Amount } from './amount.model';

export interface GetOrderItemResponseBody {
    hash: string;
    ledger: number;
    validated: boolean;
    timestamp: string;
    fee: string;
    action: string;
    type: OrderType;
    direction: PaymentDirection;
    order: object;
    balance_changes: Array<Amount>;
    order_changes: Array<object>;
    success: boolean;
}

