/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { PaymentItem } from './payment-item.model';

export interface GetPaymentListResponseBody {
    success: boolean;
    payments: Array<PaymentItem>;
}

