/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { state } from '';
import { Address } from './address.model';
import { PaymentAmount } from './payment-amount.model';
import { MemoItem } from './memo-item.model';

export interface GetPaymentItemRawResponse {
    hash: string;
    ledger: string;
    state: state;
    source_account: Address;
    destination_account?: Address;
    amount: PaymentAmount;
    currency: string;
    issuer: string;
    direction: string;
    timestamp: string;
    fee: string;
    memos: Array<MemoItem>;
    success: boolean;
}

