/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */


export interface GetOrderListResponseBody {
    ledger: number;
    validated: boolean;
    orders: Array<object>;
    success: boolean;
}

