/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Amount } from './amount.model';

export interface GetWalletBalanceReponseBody {
    success: boolean;
    ledger: number;
    balances: Array<Amount>;
}

