/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { OrderType } from './enums';
import { Amount } from './amount.model';

export interface OrderItem {
    type: OrderType;
    taker_pays: Amount;
    taker_gets: Amount;
}

