/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Address } from './address.model';
import { Amount } from './amount.model';

export interface OrderBookItem {
    order_maker: Address;
    passive: boolean;
    price: Amount;
    sell: boolean;
    sequence?: number;
    taker_gets_funded: Amount;
    taker_gets_total: Amount;
    taker_pays_funded: Amount;
    taker_pays_total: Amount;
}

