/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Address } from './address.model';
import { PaymentAmount } from './payment-amount.model';
import { PaymentDirection } from './enums';
import { MemoItem } from './memo-item.model';

export interface PaymentItem {
    hash: string;
    ledger: string;
    source_account: Address;
    destination_account?: Address;
    amount: PaymentAmount;
    direction: PaymentDirection;
    timestamp: string;
    fee: string;
    memos?: Array<MemoItem>;
}

