/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { OrderState } from './enums';

export interface PostOrderItemResponseBody {
    order: object;
    hash: string;
    ledger: string;
    state: OrderState;
    success: boolean;
}

