/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Secret } from './secret.model';

export interface PostPaymentItemRequestBody {
    secret: Secret;
    payment: object;
}

