/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */


export interface PostPaymentItemRawResponse {
    success: boolean;
    hash: string;
    status_url: string;
}

