/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Secret } from './secret.model';
import { OrderItem } from './order-item.model';

export interface PostOrderItemRequestBody {
    secret: Secret;
    order: OrderItem;
}

