/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */


export interface TransactionAmount {
    value: string;
    currency: string;
    issuer?: string;
    counterparty?: string;
}

